version: '3.7'

services:

  vpn:
    build:
      context: ./openvpnsetup
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      - private
    ports:
      - "0.0.0.0:1194:1194"
    volumes:
      - "./vpnconfig:/root/vpnsetup/vpnconfig:z"

networks:
  private:


